<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA1w4w1l\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA1w4w1l/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerA1w4w1l.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerA1w4w1l\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerA1w4w1l\appProdProjectContainer([
    'container.build_hash' => 'A1w4w1l',
    'container.build_id' => 'b9880370',
    'container.build_time' => 1714119126,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA1w4w1l');
