<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHhtwvkv\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHhtwvkv/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerHhtwvkv.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerHhtwvkv\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerHhtwvkv\appProdProjectContainer([
    'container.build_hash' => 'Hhtwvkv',
    'container.build_id' => 'fe2c9d7e',
    'container.build_time' => 1714122766,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHhtwvkv');
